server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: "Doppelkopf"
  main:
    banner-mode: off
  jackson:
    serialization:
      indent-output: true
  liquibase:
    # Disable liquibase by default in this configuration.
    # This value should be explicitly overridden in the corresponding profiles if necessary.
    enabled: false
  jpa:
    hibernate:
      # This value should be explicitly overridden in the corresponding profiles if necessary.
      ddl-auto: none

management:
  endpoints:
    web:
      exposure:
        include:
          - "health"
          - "info"
          - "openapi"
          - "swaggerui"
    jmx:
      exposure:
        include:
          - "health"
          - "info"
    access:
      # Prevent leaking sensitive actuator endpoints unless explicitly configured in this configuration.
      default: none
  health:
    defaults:
      enabled: false
    db:
      enabled: true
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      access: none